### PR TITLE
Upgrade all dependencies, including prettier

### PR DESCRIPTION
**Pull request by stefanmaric**
Prettier is already at version 1.9, this PR mainly addresses that.

I've manually checked changelogs of packages with `major` updates in search for possible breaking changes but I found none.

Build runs smoothly, test have passed, and I've tested these changes against some real projects (using `npm link`). Everything looks good.

The only dependency I wasn't able to upgrade was `babel-preset-node-module`. Version 2 has modules disabled by default and there's what I think is a bug that doesn't let you override that option. These arguments to Object#assign seem to be in the wrong order: https://github.com/sheerun/babel-preset-node-module/commit/6325ea49963b19f805021bb6d349843bded519a8#diff-168726dbe96b3ce427e7fedce31bb0bcR100

Probably, once it is released, babel-preset-env@7 would be sufficient for this project.

### CODE REVIEW

**Comment by stefanmaric** [comment]
Well, I retract, [jest dropped support for node@4 on version 22](https://github.com/facebook/jest/blob/master/CHANGELOG.md#chore--maintenance-1). But this should only affect tests on node@4 specifically: 

Should I downgrade jest to 21?

**Comment by sheerun** [comment]
To be honest I wouldn't upgrade any dev tools because they don't affect distribution code.

**Comment by stefanmaric** [comment]
> To be honest I wouldn't upgrade any dev tools because they don't affect distribution code.

But not like it is going to harm, right? :)

I replaced the last commit to keep jest on v21 and everything seems ok.

I can close this PR and open one that omits devDependencies. It's close to zero effort, just let me know what do you prefer.

**Comment by sheerun** [comment]
It's ok, thank you :)

**Pull request merged**
