### PR TITLE
Fix support for node LTS

### PR DESCRIPTION
**Pull request by neftaly**
I couldn't run or build this on my CI infra, so fixed the Babel config. Also added/removed missing/unused modules.

### CODE REVIEW

**Comment by neftaly** [comment]
Just realised that tests are run on src (not just dist?), which means further babel issues for the repo itself. Will look into it next week.

**Comment by sheerun** [comment]
Hmm, I get following errors when running this on my mac on node 4:

> prettier-standard@2.0.0 test /Users/sheerun/Source/Projects/prettier-standard
> run NODE_ENV=test jest

 FAIL  src/format-files.test.js
  ● Test suite failed to run

    SyntaxError: Unexpected reserved word

      at transformAndBuildScript (node_modules/jest/node_modules/jest-cli/node_modules/jest-runtime/build/transform.js:320:12)
      at emitTwo (events.js:87:13)

 FAIL  src/message.test.js
  ● Test suite failed to run

    SyntaxError: Unexpected reserved word

      at transformAndBuildScript (node_modules/jest/node_modules/jest-cli/node_modules/jest-runtime/build/transform.js:320:12)
      at emitTwo (events.js:87:13)

Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        0.787s
Ran all test suites.
npm ERR! Test failed.  See above for more details.

**Comment by sheerun** [comment]
@neftaly I've published 2.0.2 that should fix this issue, could you check?

**Comment by neftaly** [comment]
Looks like we'll be using something else for this. Just FYI you can just clone and rebase in future, to save copying and pasting the PR (fe8b226 6054034 88a37d0 bb220c0 7f60f37). Cheers!

**Comment by sheerun** [comment]
Could I know what you want to use? :)

**Comment by neftaly** [comment]
Sure! I actually [forked](https://github.com/dtinth/prettier-standard-formatter/pull/10) prettier-standard-formatter.

**Comment by sheerun** [comment]
Mind to tell what I could improve in this package compared to your fork?

**Pull request closed without merging**
